FROM php:7-fpm


# If you wish to install new extensions for php-fpm, this is where you need to add them
# Make sure your extension is not already installed (you can check in localhost:8080/info)
# To add new extensions take a look at https://hub.docker.com/_/php in the "How to install more PHP extensions section"